on:
    workflow_call:
        inputs:
          DOCKER_HOST:
             required: true
             type: string

          DOCKER_REPO:
             required: true
             type: string

          release_version:
             required: false
             type: string

          DOCKER_USERNAME:
             required: true
             type: string

        secrets:
                
            DOCKER_PASSWORD:
                description: 'password for Docker Hub'
                required: true



jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        outputs:
            repo_digests: ${{ steps.set-variable.outputs.repo_digests }}


        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                registry: ${{ inputs.DOCKER_HOST }}
                username: ${{ inputs.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: build and push docker image
              run: |
                docker build -t ${{ inputs.DOCKER_USERNAME }}/${{ inputs.DOCKER_REPO }}:${{ inputs.release_version }} .
                docker push ${{ inputs.DOCKER_USERNAME }}/${{ inputs.DOCKER_REPO }}:${{ inputs.release_version }}${{ github.run_number }}	