on:
    workflow_call:
        inputs:
          DOCKER_HOST:
             required: true
             type: string

          DOCKER_REPO:
             required: true
             type: string

          release_version:
             required: false
             type: string

        secrets:
            usermame:
                description: Username for Docker Hub
                required: true
                
            password:
                description: Password for Docker Hub
                required: true



jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        outputs:
            repo_digests: ${{ steps.set-variable.outputs.repo_digests }}


        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                registry: docker.io
                username: ${{ secrets.username }}
                password: ${{ secrets.password }}

            - name: build and push docker image
              run: |
                docker build -t ${{ inputs.DOCKER_HOST }}/${{ inputs.DOCKER_REPO }}:${{ inputs.release_version }} .
                docker push ${{ inputs.DOCKER_HOST }}/${{ inputs.DOCKER_REPO }}:${{ inputs.release_version }}-${{ github.run_number }}	